server:
  port: "8080"
database:
  host: "localhost"
  port: "5432"
  username: "postgres"
  password: "postgres"
  dbname: "postgres_template_be"
  sslmode: "disable"
logger:
  globalMinLevel: "debug"
  json: false
error:
  0: "unknown error"
  1: "bind error"
  2: "validate error"
