version: "2"
sql:
  - engine: "postgresql"
    queries: "../src/repository/sqlcrepo/sqlc/query.sql"
    schema: "../migration"
    gen:
      go:
        package: "sqlc"
        out: "../src/repository/sqlcrepo/sqlc"