version: "2"
sql:
  - engine: "postgresql"
    queries: "../internal/repository/sqlcrepo/sqlc/query.sql"
    schema: "../migration"
    gen:
      go:
        package: "sqlc"
        out: "../internal/repository/sqlcrepo/sqlc"