services:
  bff:
    container_name: bff
    build:
      context: ../service/bff
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    networks:
      - backend
    depends_on:
      - postgres

  postgres:
    container_name: postgres
    image: postgres:15.2-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres_template_be
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    restart: always
    networks:
      - backend

networks:
  backend:
    name: backend

volumes:
  postgres-data:
