server:
  port: ":8080"
database:
  host: "localhost"
  port: 5432
  dbname: "example"
  username: "postgres"
  password: "postgres"
  sslmode: "disable"
logger:
  globalMinLevel: "debug"
  json: "false"
